services:
  leaders:
    container_name: speed-leaders
    build: leaders
    image: localhost:32000/speed-leaders:local
    command: echo Do not start leaders during docker compose up

  workers:
    container_name: speed-workers
    build: workers
    image: localhost:32000/speed-workers:local
    command: echo Do not start workers during docker compose up

  zookeeper:
    container_name: speed-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka-network

  kafka:
    container_name: speed-kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Expose 9092 for external traffic
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: speed-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_EXTERNAL://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_EXTERNAL://host.docker.internal:9092,PLAINTEXT_INTERNAL://speed-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    networks:
      - kafka-network

  first:
    container_name: speed-first
    build: microservices/first
    image: localhost:32000/speed-first:local
    ports:
      - 5001:5001
    depends_on:
      - firstdb
      - kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: firstdb
      POSTGRES_PORT: 5432

  firstdb:
    container_name: speed-firstdb
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: firstdb
      
  optimizer:
    container_name: speed-optimizer
    depends_on:
      - optdb
    build: microservices/optimizer
    image: localhost:32000/speed-optimizer:local
    ports:
      - 5002:5002

  optdb:
    container_name: speed-optdb
    image: mongo
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

networks:
  kafka-network:
    driver: bridge
