apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: firstdb
            - name: POSTGRES_PASSWORD
              value: test
            - name: POSTGRES_USER
              value: test
          image: ghcr.io/jakejack13/speed-first
          name: speed-first
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
      restartPolicy: Always
