apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: optimizer
  name: optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: optimizer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/speed-default: "true"
        io.kompose.service: optimizer
    spec:
      containers:
        - image: ghcr.io/jakejack13/speed-optimizer
          name: speed-optimizer
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
      restartPolicy: Always
