apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizer
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
        - image: ghcr.io/jakejack13/speed-optimizer:test
          name: speed-optimizer
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
      restartPolicy: Always
