apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo-kafka
  template:
    metadata:
      labels:
        app: zoo-kafka
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
          image: confluentinc/cp-kafka:latest
          name: speed-kafka
          ports:
            - containerPort: 29092
              hostPort: 29092
              protocol: TCP
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          name: speed-zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
      restartPolicy: Always
